/* Per-industry content for Nearwork industry landing pages.
   Keyed by industry name (matches roles-data.js). Structural copy
   (managed steps, generic FAQ, candidates) is generated by the renderer. */
window.NW_CONTENT = {
"Software Development": {
  noun:"engineer", metric:"Code",
  lead:"Product-minded engineers across every stack — sourced, tested on real problems, and fully managed by Nearwork from Colombia.",
  poolLine:"Colombia graduates thousands of CS and software engineers every year, and a decade of nearshore product work built a deep bench of senior builders in US time zones.",
  availList:["Senior builders across frontend, backend, mobile and AI","Real overlap with US and Canadian standups and sprints","Tested on live coding and system-design problems, not trivia","Comfortable in modern stacks, CI/CD and code review culture"],
  strip:[["12,000+","vetted engineers"],["C1","English standard"],["~14 days","brief to shortlist"],["58%","less than a US hire"]],
  criteria:[
    ["Coding & problem solving","96","Live problems in your stack — not algorithm trivia — scored by senior engineers."],
    ["System design","93","Designs services that scale, reason about trade-offs, and document decisions."],
    ["Code quality & review","94","Writes tested, readable code and gives sharp, kind reviews."],
    ["English & communication","95","C1 fluency that keeps standups, PRs and docs clear across time zones."],
    ["Product judgment","91","Pushes back on vague tickets and ships the thing that moves the metric."],
    ["Ramp speed","90","Gets productive in an unfamiliar codebase fast and flags what is missing."]
  ],
  cost:{us:"$135k / year", uspct:100, nw:"$55k / year", nwpct:41, save:"Save $80k/yr"},
  faqs:[
    ["Can they work in our exact stack?","We match on stack and test candidates on problems close to your codebase. You see the assessment recordings and scores before you decide, so there are no surprises on day one."],
    ["Junior, senior or lead?","All three. Tell us the seniority and we scope the assessment accordingly — from strong mid-level builders to staff engineers who can own a system."]
  ]
},
"Marketing & Content": {
  noun:"marketer", metric:"Craft",
  lead:"Growth, content, SEO and demand-gen specialists who can own a channel — sourced, assessed on real work, and managed by Nearwork.",
  poolLine:"A booming regional startup scene created a deep pool of bilingual marketers who write, rank and run paid channels for US audiences.",
  availList:["Content, SEO, paid, lifecycle and growth specialists","Write natively for US and Canadian audiences","Assessed on portfolios and live briefs, not buzzwords","Fluent in HubSpot, GA4, Ahrefs, Webflow and the modern stack"],
  strip:[["4,800+","vetted marketers"],["C1","English standard"],["~14 days","brief to shortlist"],["60%","less than a US hire"]],
  criteria:[
    ["Writing & messaging","95","Clear, on-brand copy for US audiences — scored on a live brief, not a résumé."],
    ["Channel expertise","93","Real depth in SEO, paid, lifecycle or content — not a shallow generalist."],
    ["Analytical thinking","92","Reads the funnel, runs experiments and reports on what actually moved."],
    ["English fluency","96","C1: writes and presents natively for US and Canadian markets."],
    ["Tooling","91","Productive in HubSpot, GA4, Ahrefs, Webflow, Figma and the ad platforms."],
    ["Ownership","90","Takes a channel end-to-end and defends a point of view with data."]
  ],
  cost:{us:"$85k / year", uspct:100, nw:"$34k / year", nwpct:40, save:"Save $51k/yr"},
  faqs:[
    ["Can they write for our brand voice?","Yes. We run a live writing brief in your voice as part of the assessment, so you see real samples — not a portfolio of someone else's edits — before you hire."],
    ["Generalist or specialist?","Either. We can staff a T-shaped generalist for an early team, or a deep specialist in SEO, paid or lifecycle when you need one channel run properly."]
  ]
},
"Data & Analytics": {
  noun:"analyst", metric:"Rigor",
  lead:"Analysts, data engineers and scientists who turn messy data into decisions — sourced, tested on real datasets, and managed by Nearwork.",
  poolLine:"Strong STEM universities and a mature analytics scene give Colombia a deep bench of data talent fluent in SQL, Python and the modern warehouse.",
  availList:["Analysts, analytics engineers and data scientists","Overlap with US business hours for live analysis","Tested on real SQL, modeling and dashboarding tasks","Fluent in dbt, Snowflake, BigQuery, Python and BI tools"],
  strip:[["3,600+","vetted data pros"],["C1","English standard"],["~14 days","brief to shortlist"],["58%","less than a US hire"]],
  criteria:[
    ["SQL & data modeling","95","Writes correct, performant SQL and models data that others can trust."],
    ["Statistical reasoning","92","Chooses the right method, sizes the effect and avoids the obvious traps."],
    ["Tooling & pipelines","93","Productive in dbt, Snowflake, BigQuery, Python and orchestration."],
    ["Business translation","91","Turns a vague question into the right metric and a clear answer."],
    ["English & communication","95","C1: explains findings to non-technical stakeholders without hand-waving."],
    ["Data quality instinct","90","Spots the broken join and the silent null before they reach a dashboard."]
  ],
  cost:{us:"$120k / year", uspct:100, nw:"$50k / year", nwpct:42, save:"Save $70k/yr"},
  faqs:[
    ["Analyst, analytics engineer or scientist?","All three, scoped to your stack. Tell us whether you need dashboards, pipelines or modeling and we tailor the assessment to match."],
    ["Do they test on real data problems?","Yes — SQL and modeling exercises close to your domain, scored by senior data people. You review the work before deciding."]
  ]
},
"Cloud & DevOps": {
  noun:"engineer", metric:"Ops",
  lead:"Infrastructure, CI/CD and reliability engineers who keep production healthy — sourced, tested on real ops scenarios, and managed by Nearwork.",
  poolLine:"Years of nearshore platform work built a bench of engineers who run real cloud infrastructure for US companies, in US time zones.",
  availList:["Platform, SRE, CI/CD and cloud infrastructure engineers","On-call-capable overlap with US business hours","Tested on real infra, incident and pipeline scenarios","Fluent in AWS, GCP, Kubernetes, Terraform and observability"],
  strip:[["2,900+","vetted DevOps pros"],["C1","English standard"],["~14 days","brief to shortlist"],["58%","less than a US hire"]],
  criteria:[
    ["Cloud infrastructure","95","Designs and runs resilient infra on AWS, GCP or Azure with real cost sense."],
    ["CI/CD & automation","93","Builds pipelines and automation that make deploys boring — the goal."],
    ["Reliability & incident response","92","Debugs production calmly, writes the postmortem and prevents the repeat."],
    ["Security & compliance","90","Bakes least-privilege, secrets hygiene and audit trails in by default."],
    ["English & communication","95","C1: clear in incidents, runbooks and cross-team coordination."],
    ["IaC discipline","91","Everything as code in Terraform — reviewable, repeatable, documented."]
  ],
  cost:{us:"$145k / year", uspct:100, nw:"$60k / year", nwpct:41, save:"Save $85k/yr"},
  faqs:[
    ["Can they join our on-call rotation?","Yes. Colombia's time zone overlaps US business hours, and candidates are screened for incident response. We set on-call expectations up front."],
    ["Which clouds do they know?","AWS, GCP and Azure, plus Kubernetes and Terraform. We match to your platform and test on scenarios close to your environment."]
  ]
},
"Design": {
  noun:"designer", metric:"Craft",
  lead:"Product, brand and UX designers who ship polished, thoughtful work — sourced, assessed on portfolios and live briefs, and managed by Nearwork.",
  poolLine:"A vibrant regional design community produces product and brand designers who work daily with US startups and design systems.",
  availList:["Product, UX, brand and design-system specialists","Overlap with US design reviews and sprints","Assessed on portfolios and a live design brief","Fluent in Figma, prototyping and design-system thinking"],
  strip:[["2,400+","vetted designers"],["C1","English standard"],["~14 days","brief to shortlist"],["58%","less than a US hire"]],
  criteria:[
    ["Visual & interaction craft","95","Polished, considered work — spacing, type and states that hold up."],
    ["Product thinking","93","Designs for the user and the metric, not just the mock."],
    ["Systems & consistency","92","Builds and respects design systems so the whole product feels one."],
    ["Prototyping & handoff","91","Prototypes fast and hands off specs engineers can build without guessing."],
    ["English & communication","95","C1: presents and defends design decisions clearly in reviews."],
    ["Feedback & iteration","90","Takes critique well and iterates toward the strongest version quickly."]
  ],
  cost:{us:"$105k / year", uspct:100, nw:"$44k / year", nwpct:42, save:"Save $61k/yr"},
  faqs:[
    ["Product or brand designer?","Both. Tell us whether you need product/UX depth or brand and marketing design, and we scope the portfolio review and live brief accordingly."],
    ["Do they know design systems?","Yes — systems thinking is part of the assessment. Candidates show how they build and maintain components, tokens and consistency at scale."]
  ]
},
"Product & Project Management": {
  noun:"PM", metric:"Delivery",
  lead:"Product managers and delivery leads who keep teams shipping the right thing — sourced, assessed on real scenarios, and managed by Nearwork.",
  poolLine:"A mature startup ecosystem produced PMs and delivery leads who run discovery, roadmaps and sprints for US product teams.",
  availList:["Product managers, project managers and delivery leads","Overlap with US standups, planning and reviews","Assessed on prioritization and stakeholder scenarios","Fluent in Jira, Linear, Notion and modern PM craft"],
  strip:[["2,200+","vetted PMs"],["C1","English standard"],["~14 days","brief to shortlist"],["58%","less than a US hire"]],
  criteria:[
    ["Prioritization & judgment","94","Cuts scope to what matters and can explain exactly why."],
    ["Discovery & user insight","92","Talks to users, frames the problem and validates before building."],
    ["Delivery & execution","93","Keeps sprints honest, unblocks the team and hits the date."],
    ["Stakeholder communication","95","C1 fluency that aligns engineering, design and leadership."],
    ["Data literacy","91","Reads the metrics, sets targets and measures whether it worked."],
    ["Ownership","90","Owns outcomes, not tickets — and holds the line on quality."]
  ],
  cost:{us:"$125k / year", uspct:100, nw:"$52k / year", nwpct:42, save:"Save $73k/yr"},
  faqs:[
    ["Product manager or project manager?","Either — they are different roles and we assess for the one you need, whether that is discovery and roadmap ownership or delivery and coordination."],
    ["How do you test PM skill?","Through prioritization exercises, a stakeholder role-play and a discovery scenario, scored by senior PMs. You review the results before choosing."]
  ]
},
"Finance & Accounting": {
  noun:"accountant", metric:"Accuracy",
  lead:"Bookkeepers, analysts and controllers you can trust with the numbers — sourced, tested for accuracy, and managed by Nearwork.",
  poolLine:"Colombia has a large, well-trained accounting workforce familiar with US GAAP-style books and the modern finance stack.",
  availList:["Bookkeepers, FP&A analysts, controllers and AP/AR","Overlap with US close cycles and reporting","Tested on real reconciliation and modeling tasks","Fluent in QuickBooks, NetSuite, Excel and reporting tools"],
  strip:[["3,300+","vetted finance pros"],["C1","English standard"],["~14 days","brief to shortlist"],["60%","less than a US hire"]],
  criteria:[
    ["Accuracy & attention to detail","96","Reconciles to the penny and catches the error before the close."],
    ["Accounting knowledge","93","Solid on accrual accounting, month-end and US-style reporting."],
    ["Financial modeling & FP&A","91","Builds clean models and forecasts leadership can actually use."],
    ["Systems & tooling","92","Productive in QuickBooks, NetSuite, Excel and reporting stacks."],
    ["English & communication","95","C1: clear with vendors, auditors and leadership alike."],
    ["Discretion & integrity","94","Handles sensitive financials with the care they demand."]
  ],
  cost:{us:"$85k / year", uspct:100, nw:"$34k / year", nwpct:40, save:"Save $51k/yr"},
  faqs:[
    ["Do they know US accounting practices?","Yes. Candidates are screened on accrual accounting, month-end close and US-style reporting, and tested on reconciliation and modeling tasks close to your books."],
    ["Bookkeeper or controller?","The full range — from AP/AR and bookkeeping to FP&A analysts and controllers. We scope the assessment to the seniority you need."]
  ]
},
"Operations & Administration": {
  noun:"coordinator", metric:"Ops",
  lead:"Coordinators, executive assistants and operations leads who keep the business running — sourced, assessed on real tasks, and managed by Nearwork.",
  poolLine:"A deep service-economy workforce gives Colombia reliable, organized operators who run back-office and executive support for US teams.",
  availList:["Executive assistants, ops coordinators and ops leads","Real-time overlap with US business hours","Assessed on organization, judgment and tooling","Fluent in the modern ops stack — Notion, Slack, Asana, sheets"],
  strip:[["3,000+","vetted ops pros"],["C1","English standard"],["~14 days","brief to shortlist"],["58%","less than a US hire"]],
  criteria:[
    ["Organization & follow-through","95","Nothing drops — tracks the details and closes every loop."],
    ["Judgment & prioritization","92","Knows what is urgent, what can wait and when to escalate."],
    ["Process & documentation","91","Turns chaos into a repeatable process and writes it down."],
    ["Tooling","92","Productive across Notion, Slack, Asana, sheets and automation."],
    ["English & communication","95","C1: professional in writing and on calls with your stakeholders."],
    ["Discretion","90","Handles calendars, contracts and sensitive info with care."]
  ],
  cost:{us:"$62k / year", uspct:100, nw:"$26k / year", nwpct:42, save:"Save $36k/yr"},
  faqs:[
    ["Executive assistant or operations lead?","Both, and everything in between. Tell us whether you need EA support, ops coordination or someone to own a function, and we match accordingly."],
    ["How do you test for reliability?","Through task-based scenarios that measure organization, judgment and follow-through, plus reference checks. You see the results before you hire."]
  ]
},
"Sales": {
  noun:"rep", metric:"Quota",
  lead:"SDRs, AEs and revenue operators who hit quota — sourced, assessed on live call scenarios, and managed by Nearwork.",
  poolLine:"A decade of nearshore sales work built a bench of persuasive, English-fluent reps who sell to US and Canadian buyers every day.",
  availList:["SDRs, AEs, sales ops and revenue operators","Real-time overlap with US selling hours","Assessed on live call and objection-handling scenarios","Fluent in Salesforce, HubSpot, Outreach and the sales stack"],
  strip:[["2,700+","vetted sales pros"],["C1","English standard"],["~14 days","brief to shortlist"],["58%","less than a US hire"]],
  criteria:[
    ["Prospecting & pipeline","93","Builds pipeline consistently and works a list without babysitting."],
    ["Discovery & objection handling","94","Runs real discovery and handles objections without a script."],
    ["Closing & follow-through","92","Moves deals forward and does the unglamorous follow-up that wins."],
    ["English & rapport","96","C1: builds trust fast with US and Canadian buyers on the phone."],
    ["CRM discipline","91","Keeps Salesforce or HubSpot clean so the forecast is real."],
    ["Coachability","90","Takes feedback on calls and improves week over week."]
  ],
  cost:{us:"$90k / year", uspct:100, nw:"$38k / year", nwpct:42, save:"Save $52k/yr"},
  faqs:[
    ["SDR or full-cycle AE?","Both. We assess for the motion you run — top-of-funnel prospecting, full-cycle closing, or sales ops — with scenarios that match your buyer."],
    ["How do you test selling ability?","Through live call role-plays scored on discovery, objection handling and rapport by senior sales leaders. You hear the recordings before deciding."]
  ]
},
"Customer Support": {
  noun:"support pro", metric:"Empathy",
  lead:"Empathetic, English-fluent support professionals — sourced, assessed for what actually matters in support, and fully managed by Nearwork.",
  poolLine:"A decade of nearshore BPO built one of the region's deepest support talent pools — fluent English, US-hours overlap and a genuine service culture.",
  availList:["Career support professionals, not gig fillers","Real-time overlap with US and Canadian business hours","Warm, service-first culture customers actually feel","Experienced across chat, email, phone and social support"],
  strip:[["3,100+","vetted support pros"],["C1","English standard"],["~14 days","brief to shortlist"],["55%","less than a US hire"]],
  criteria:[
    ["Empathy & tone","97","Reads emotion, mirrors tone and de-escalates without a script."],
    ["Problem resolution","93","First-contact resolution and root-cause thinking, knows when to escalate."],
    ["Written & spoken English","95","C1: clear, warm and professional across chat, email and calls."],
    ["Composure under pressure","92","Holds CSAT steady through volume, anger and back-to-backs."],
    ["CRM & tooling","91","Day-one productive in Zendesk, Intercom, Service Cloud and Gorgias."],
    ["Product ramp speed","89","Learns your product and macros fast, then documents the gaps."]
  ],
  cost:{us:"$58k / year", uspct:100, nw:"$26k / year", nwpct:45, save:"Save $32k/yr"},
  faqs:[
    ["How do you test for empathy, not just experience?","Every candidate works through role-play scenarios scored by senior support leads on tone, listening and resolution. You see the recordings and scores before you decide."],
    ["Which support channels can they cover?","Chat, email, phone and social. We match to your channel mix and tools — Zendesk, Intercom, Gorgias, Service Cloud or Front."]
  ]
},
"Human Resources & Recruiting": {
  noun:"recruiter", metric:"People",
  lead:"Recruiters, HR generalists and people-ops specialists who build great teams — sourced, assessed on real scenarios, and managed by Nearwork.",
  poolLine:"A large, people-first professional workforce gives Colombia strong recruiters and HR partners fluent in US hiring and people practices.",
  availList:["Recruiters, HR generalists and people-ops specialists","Overlap with US interview loops and business hours","Assessed on sourcing, screening and HR scenarios","Fluent in Greenhouse, Lever, BambooHR and the HR stack"],
  strip:[["2,000+","vetted HR pros"],["C1","English standard"],["~14 days","brief to shortlist"],["58%","less than a US hire"]],
  criteria:[
    ["Sourcing & pipeline","93","Finds and engages strong candidates in competitive markets."],
    ["Screening & judgment","92","Reads a résumé and a conversation for real signal, not keywords."],
    ["Candidate experience","94","Keeps candidates warm and informed — your brand in every touch."],
    ["HR & compliance knowledge","91","Solid on people ops, policy and the basics of US employment norms."],
    ["English & communication","96","C1: professional and warm with candidates and hiring managers."],
    ["Discretion","90","Handles compensation and sensitive people matters with care."]
  ],
  cost:{us:"$80k / year", uspct:100, nw:"$33k / year", nwpct:41, save:"Save $47k/yr"},
  faqs:[
    ["Recruiter or HR generalist?","Both. Tell us whether you need full-cycle recruiting, sourcing support or a people-ops generalist, and we scope the assessment to the role."],
    ["Do they know US hiring practices?","Yes — candidates are screened on US-style recruiting workflows, candidate experience and the fundamentals of people operations."]
  ]
},
"IT & Technical Support": {
  noun:"technician", metric:"Resolve",
  lead:"Helpdesk and systems support that keeps your people running — sourced, tested on real tickets, and managed by Nearwork.",
  poolLine:"A deep IT services workforce gives Colombia reliable helpdesk and systems technicians who support US employees in real time.",
  availList:["Helpdesk, desktop and systems support technicians","Real-time overlap with US business hours","Tested on real troubleshooting and ticket scenarios","Fluent in Jira Service, Intune, Google Workspace and M365"],
  strip:[["2,100+","vetted IT pros"],["C1","English standard"],["~14 days","brief to shortlist"],["58%","less than a US hire"]],
  criteria:[
    ["Troubleshooting","95","Diagnoses fast, fixes the root cause and documents the fix."],
    ["Systems & tooling","92","Comfortable across M365, Google Workspace, Intune and MDM."],
    ["Ticket discipline","91","Keeps the queue moving and every ticket clean and updated."],
    ["Customer-facing patience","94","Helps non-technical people calmly, without condescension."],
    ["English & communication","95","C1: clear in tickets, calls and step-by-step instructions."],
    ["Security awareness","90","Follows access, patching and phishing hygiene by default."]
  ],
  cost:{us:"$70k / year", uspct:100, nw:"$30k / year", nwpct:43, save:"Save $40k/yr"},
  faqs:[
    ["Tier 1 or systems admin?","Both — from tier 1 helpdesk to systems and endpoint administration. We match the assessment to the depth you need."],
    ["Can they support our US employees live?","Yes. Colombia overlaps US business hours, so tickets and calls are handled in real time, not overnight."]
  ]
},
"Business & Systems Analysis": {
  noun:"analyst", metric:"Analysis",
  lead:"Analysts who bridge business and technology — sourced, assessed on real requirements scenarios, and managed by Nearwork.",
  poolLine:"A mature enterprise and consulting sector produced business and systems analysts fluent in requirements, process and US-style delivery.",
  availList:["Business analysts, systems analysts and process leads","Overlap with US stakeholder and delivery meetings","Assessed on requirements and process scenarios","Fluent in Jira, Confluence, SQL and BPMN"],
  strip:[["1,700+","vetted analysts"],["C1","English standard"],["~14 days","brief to shortlist"],["58%","less than a US hire"]],
  criteria:[
    ["Requirements & elicitation","94","Draws out what stakeholders actually need and writes it clearly."],
    ["Process modeling","92","Maps and improves processes others can follow and build from."],
    ["Technical fluency","91","Reads data, writes SQL and speaks the engineers' language."],
    ["Stakeholder management","93","Aligns business and tech and keeps everyone rowing together."],
    ["English & communication","96","C1: precise in specs, docs and cross-functional meetings."],
    ["Documentation","90","Produces specs and diagrams that leave nothing to guess."]
  ],
  cost:{us:"$105k / year", uspct:100, nw:"$44k / year", nwpct:42, save:"Save $61k/yr"},
  faqs:[
    ["Business or systems analyst?","Either. We assess for requirements and process work, or for the more technical systems-analysis side, depending on what your delivery needs."],
    ["How do you test analysis skill?","With a requirements-elicitation scenario and a process-modeling exercise scored by senior analysts. You review the output before deciding."]
  ]
},
"Cybersecurity": {
  noun:"security engineer", metric:"Defense",
  lead:"Security engineers and analysts who protect your stack — sourced, tested on real security scenarios, and managed by Nearwork.",
  poolLine:"Growing demand for nearshore security built a bench of Colombian engineers and analysts who defend US environments in real time.",
  availList:["Security engineers, SOC analysts and GRC specialists","Overlap with US business hours and incident windows","Tested on real detection and hardening scenarios","Fluent in SIEM, cloud security, IAM and compliance frameworks"],
  strip:[["1,400+","vetted security pros"],["C1","English standard"],["~14 days","brief to shortlist"],["58%","less than a US hire"]],
  criteria:[
    ["Threat detection & response","94","Spots the anomaly, triages fast and drives the incident to closure."],
    ["Cloud & infrastructure security","93","Hardens cloud, identity and networks against real attack paths."],
    ["Vulnerability management","91","Finds, prioritizes and closes what matters — not just the scanner noise."],
    ["Compliance & GRC","90","Fluent in SOC 2, ISO 27001 and the controls auditors expect."],
    ["English & communication","95","C1: clear in incidents, reports and executive briefings."],
    ["Security mindset","92","Thinks like an attacker and defends by default."]
  ],
  cost:{us:"$135k / year", uspct:100, nw:"$57k / year", nwpct:42, save:"Save $78k/yr"},
  faqs:[
    ["SOC analyst or security engineer?","Both, plus GRC. Tell us whether you need detection and response, cloud hardening or compliance work, and we scope the assessment to match."],
    ["Do they know compliance frameworks?","Yes — candidates are screened on SOC 2, ISO 27001 and common controls, and tested on scenarios relevant to your environment."]
  ]
},
"Healthcare Support": {
  noun:"coordinator", metric:"Care",
  lead:"Patient coordination and medical administration handled with care — sourced, assessed for accuracy and empathy, and managed by Nearwork.",
  poolLine:"A large trained health-services workforce gives Colombia reliable, HIPAA-aware coordinators and medical admins for US practices.",
  availList:["Patient coordinators, medical admins and billing support","Real-time overlap with US clinic hours","Assessed for accuracy, empathy and privacy awareness","Familiar with EHRs, scheduling and US healthcare workflows"],
  strip:[["1,500+","vetted healthcare pros"],["C1","English standard"],["~14 days","brief to shortlist"],["58%","less than a US hire"]],
  criteria:[
    ["Accuracy & attention to detail","95","Gets patient records, codes and schedules exactly right."],
    ["Empathy & patient communication","94","Warm, clear and calm with patients on every interaction."],
    ["Privacy & HIPAA awareness","93","Handles PHI with the discretion and rules it requires."],
    ["Systems & EHR fluency","91","Productive in common EHRs, scheduling and billing tools."],
    ["English & communication","95","C1: professional with patients, providers and payers."],
    ["Reliability","90","Dependable through high volume and sensitive situations."]
  ],
  cost:{us:"$55k / year", uspct:100, nw:"$24k / year", nwpct:44, save:"Save $31k/yr"},
  faqs:[
    ["Are they HIPAA-aware?","Yes. Candidates are screened on PHI handling and privacy practices, and we put the right agreements and safeguards in place as your Employer of Record."],
    ["Which healthcare tasks can they cover?","Patient scheduling and coordination, intake, records, prior authorizations and billing support — matched to your practice and EHR."]
  ]
},
"Legal & Admin": {
  noun:"paralegal", metric:"Precision",
  lead:"Paralegals and legal support professionals who get the details right — sourced, assessed on real tasks, and managed by Nearwork.",
  poolLine:"A large legal-services workforce gives Colombia detail-obsessed paralegals and legal admins fluent in US-style document work.",
  availList:["Paralegals, legal assistants and contract admins","Overlap with US business hours and filing windows","Assessed on drafting, review and organization tasks","Familiar with document management and e-signature tools"],
  strip:[["900+","vetted legal pros"],["C1","English standard"],["~14 days","brief to shortlist"],["58%","less than a US hire"]],
  criteria:[
    ["Accuracy & precision","96","Catches the missing clause and the wrong date every time."],
    ["Legal drafting & review","92","Drafts and reviews routine documents cleanly and consistently."],
    ["Organization & deadlines","93","Tracks matters, filings and dates so nothing slips."],
    ["Research","90","Finds the relevant precedent, form or fact efficiently."],
    ["English & communication","96","C1: precise in writing and professional with counsel and clients."],
    ["Discretion & confidentiality","94","Handles privileged material with the care it demands."]
  ],
  cost:{us:"$72k / year", uspct:100, nw:"$30k / year", nwpct:42, save:"Save $42k/yr"},
  faqs:[
    ["What legal work can they support?","Document drafting and review, contract administration, filing and matter management, legal research and general legal admin — under your supervision."],
    ["Are they a substitute for a licensed attorney?","No — they are paralegal and legal-support professionals who work under your attorneys' direction, not a replacement for licensed legal advice."]
  ]
},
"QA & Testing": {
  noun:"QA engineer", metric:"Coverage",
  lead:"Manual and automation QA engineers who ship quality — sourced, tested on real bugs, and managed by Nearwork.",
  poolLine:"A strong software sector produced QA engineers who build test coverage and automation for US product teams every day.",
  availList:["Manual QA, automation and SDET engineers","Overlap with US release and sprint cycles","Tested on real bug-finding and automation tasks","Fluent in Playwright, Cypress, Selenium and CI test suites"],
  strip:[["1,300+","vetted QA pros"],["C1","English standard"],["~14 days","brief to shortlist"],["58%","less than a US hire"]],
  criteria:[
    ["Test design & coverage","94","Designs cases that find real bugs, not just happy paths."],
    ["Bug finding & reporting","93","Reproduces cleanly and writes reports engineers can act on."],
    ["Automation","92","Builds durable automated suites in Playwright, Cypress or Selenium."],
    ["Process & CI integration","90","Wires tests into CI so quality is checked on every commit."],
    ["English & communication","95","C1: clear in bug reports, test plans and standups."],
    ["Attention to detail","91","Notices the off-by-one and the broken edge case others miss."]
  ],
  cost:{us:"$95k / year", uspct:100, nw:"$40k / year", nwpct:42, save:"Save $55k/yr"},
  faqs:[
    ["Manual or automation QA?","Both. Tell us whether you need exploratory manual testing, automation engineering or a full SDET, and we tailor the assessment."],
    ["Which automation tools?","Playwright, Cypress, Selenium and framework-specific suites, integrated into CI. We match to your stack and test on tasks close to it."]
  ]
},
"Leadership": {
  noun:"operator", metric:"Impact",
  lead:"Fractional and senior operators who can lead the work — sourced, assessed on real leadership scenarios, and managed by Nearwork.",
  poolLine:"A mature regional business scene produced experienced managers and directors who lead distributed teams for US companies.",
  availList:["Team leads, managers and fractional directors","Overlap with US leadership and planning cadences","Assessed on leadership, strategy and delivery scenarios","Proven at building and running distributed remote teams"],
  strip:[["600+","vetted leaders"],["C1","English standard"],["~14 days","brief to shortlist"],["55%","less than a US hire"]],
  criteria:[
    ["Team leadership","94","Builds, coaches and retains strong distributed teams."],
    ["Strategic thinking","93","Sets direction and connects daily work to the business goal."],
    ["Delivery & accountability","92","Owns outcomes and holds the team to a high bar."],
    ["Stakeholder communication","95","C1: credible with executives, clients and the team alike."],
    ["Operational rigor","91","Runs planning, metrics and cadence that keep teams on track."],
    ["Judgment","90","Makes the hard call with incomplete information and owns it."]
  ],
  cost:{us:"$180k / year", uspct:100, nw:"$78k / year", nwpct:43, save:"Save $102k/yr"},
  faqs:[
    ["Full-time or fractional?","Both. We can place a full-time leader to run a function, or a fractional director a few days a week to level up an existing team."],
    ["What functions can they lead?","Engineering, support, operations, marketing and more — matched to a leader with real experience running that function for US companies."]
  ]
}
};
